// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
chrome.runtime.onStartup.addListener(function(){});
(function(){function A(a){document.cookie&&-1<document.cookie.indexOf("s=1")?(l=B("st")||l,chrome.runtime.onMessage.addListener(u),b.a0&&b.a3&&chrome.contextMenus.onClicked.addListener(v),a&&f()):(document.cookie="s=1; expires=0; path=/",chrome.runtime.onMessage.addListener(u),b.a0&&b.a3&&chrome.contextMenus.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]},function(){chrome.contextMenus.onClicked.addListener(v)}),1==b.nv?w(1):"6.9.3.2"!==b.ver?(a=l,f({nv:Math.floor(Math.random()*
(a+6048E5-a+1))+a,ver:"6.9.3.2"}),setTimeout(n,2012)):2<b.nv&&b.nv<l?w():a&&f())}function w(a){var c="Khk.html?s=6930"+(new Date).getDate()+(new Date).getHours();a?(f({nv:0}),p({ea:"install"}),q("https://www.hotcleaner.com/clickclean/install-magic.html",0,c,0),q("https://www.chromeactions.com/magic-options.html",0,c,0)):(b.sv=1,x(function(a){a?(f(),C()):(f({nv:0}),p({ea:"update"}))}));setTimeout(n,1993)}function f(a){b.a0&&b.a4||(b.ui=0);a&&("nv"in a&&(b.nv=a.nv),"ver"in a&&(b.ver=a.ver));
var c=JSON.stringify(b);m="window.msg__='"+c+"'";try{chrome.storage.local.set({opt:c}),window.localStorage.setItem("opt",c)}catch(d){}a&&a.bub&&chrome.tabs.query({windowType:"normal",url:"*://*.youtube.com/*",status:"complete"},function(a){for(var c=0,d=a.length;c<d;c++)chrome.tabs.executeScript(a[c].id,{code:m})})}function u(a,c,d){if(32==a)return-1<c.tab.index&&(chrome.tabs.executeScript(c.tab.id,{code:m,runAt:"document_start"}),chrome.pageAction.show(c.tab.id)),!1;if(0==a)return!1;if(a&&6==a.id)return y(a),
!1;try{a=JSON.parse(a)}catch(h){return}if(0==a.id)d({opt:b,url:c.tab.url});else if(1==a.id)p(a.ga);else if(2==a.id)r(a.url,a.incognito);else if(3==a.id){for(var e in a.opt)e in g&&"nv"!=e&&"ver"!=e&&(b[e]=a.opt[e]);f({bub:!0})}else if(4==a.id){e=a.name;if("nv"==e||"ver"==e)return!1;e in g&&(b[e]=a.value,f({bub:!0}))}else 5==a.id?d({value:b[a.name]}):6==a.id?y(a.v):7==a.id?q("https://www.chromeactions.com/magic-options.html",0,"Khk.html?s=6930"+(new Date).getDate()+(new Date).getHours(),0):
9==a.id?d(z):10==a.id?f({nv:0}):11==a.id?chrome.windows.update(c.tab.windowId,{state:a.v?"fullscreen":"maximized"}):12==a.id&&chrome.pageAction.show(c.tab.id);return!0}function y(a){z=a;chrome.tabs.query({url:"https://www.chromeactions.com/capture-snapshot-video-frames.html"},function(c){c&&c.length?chrome.tabs.update(c[0].id,{active:!0},function(){chrome.tabs.sendMessage(c[0].id,a)}):chrome.tabs.create({url:"https://www.chromeactions.com/capture-snapshot-video-frames.html",active:!0})})}function q(a,
c,d,b){x(function(e){e?r(a,c):r(d,b)})}function r(a,c){function d(a){chrome.windows.update(a.windowId,{focused:!0})}chrome.tabs.query({url:a},function(b){if(b&&b.length)chrome.tabs.update(b[0].id,{active:!0},d);else if(c)try{chrome.windows.create({url:a,focused:!0,incognito:!0,state:"maximized"},function(){chrome.runtime.lastError&&chrome.tabs.create({url:a,active:!0},d)})}catch(h){chrome.tabs.create({url:a,active:!0},d)}else chrome.tabs.create({url:a,active:!0},d)})}function C(){chrome.tabs.create({url:"e.html",
active:!1},function(a){})}function x(a){t("HEAD","https://www.chromeactions.com/",0,"text",function(c){!c||200!=c.code&&304!=c.code?a():a(1)})}function v(a,c){if(7840==a.menuItemId){var b="https://www.youtube.com/results?search_query="+encodeURIComponent(a.selectionText);0==c.url.indexOf("https://www.youtube.com/")?chrome.tabs.update({url:b}):chrome.tabs.create({url:b,selected:!0})}}function n(){t("GET","https://clients2.google.com/service/update2/crx?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D6.9.3.2%26uc&_="+
(new Date).getTime(),null,0,function(a){})}function p(a){var c=a.ec?a.ec:"app",d=a.ea?a.ea:"unk";a=a.el?a.el:"mafy 6.9.3.2";b.uid||(b.uid=D());t("POST","https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+b.uid+"&t=event&ec="+c+"&ea="+d+"&el="+a,"text",function(){})}function t(a,c,b,e,h){var d={code:0},f=new XMLHttpRequest;f.open(a,c,!0);e&&(f.responseType=e);f.onload=function(a){d.code=this.status||0;d.data=this.response;h(d)};f.onerror=function(){h(d)};f.onabort=function(){h(d)};
try{f.send(b)}catch(F){h(d)}}function D(){var a=Math.random,c=(4294967296*a()>>>0).toString(16),b=((4294967296*a()&4294922239|16384)>>>0).toString(16),e=((4294967296*a()&3221225471|2147483648)>>>0).toString(16),a=(4294967296*a()>>>0).toString(16);8>c.length&&(c=("0000000"+c).slice(-8));8>b.length&&(b=("0000000"+b).slice(-8));8>e.length&&(e=("0000000"+e).slice(-8));8>a.length&&(a=("0000000"+a).slice(-8));return[c,b.slice(0,4),b.slice(4),e.slice(0,4),e.slice(4)+a].join("-")}function B(a){a=parseInt(window.localStorage[a]);
return isNaN(a)?null:a}var l=Date.now(),z,b,m,g={ver:"6.9.3.2",nv:1,sv:0,extURL:"",uid:"",mwvc:!0,color:"yellow",mwvct:0,mwvci:2,gap:5,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,hide:!1,ha:!1,anns:!0,cin:!0,cina:!1,cini:2,cinf:!1,cinc:1,cins:"",pt:!1,pti:0,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!0,a4:!0,a5:!1,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0},k=Object.getOwnPropertyDescriptor(chrome,"management");if(k){k.value={};k.configurable=
!1;k.writable=!1;try{Object.defineProperty(chrome,"management",k)}catch(a){}}try{chrome.runtime.setUninstallURL("https://www.chromeactions.com/magic-actions-for-youtube-support.html#chugjdc")}catch(a){}setTimeout(n,1503);(function(a,b,d){chrome.storage.local.get(a,function(c){var e;try{e=JSON.parse(a in c?c[a]:window.localStorage[a])}catch(E){e=null}d(null===e||e.constructor!==b?null:e)})})("opt",Object,function(a){var c;b=a;if(null===b||void 0===b.ver)b=g,c=!0;else{for(var d in b)d in g?typeof b[d]!==
typeof g[d]&&(b[d]=g[d],c=!0):(delete b[d],c=!0);for(d in g)d in b||(b[d]=g[d],c=!0)}b.extURL=chrome.runtime.getURL("");m="window.msg__='"+JSON.stringify(b)+"'";A(c)})})();
